Implement basic keybind Labels
DelvUI/DelvCD pull request #62
Opened 2024-07-23 06:33 UTC by Zeffuro

Don't merge yet, I need help with 2 tiny things.

1. These keybinds currently only show up when a cooldown or item is on cooldown.
2. I'd like to move `keybindHelper.UpdateKeybindHints();` to a better place as per my comment: 
// TODO: Needs to be moved to some place/event that only gets triggered on either job swap or when someone updates their hotbar
// AgentUpdateFlags ActionBarUpdate is no good because that will trigger by using actions as well apparently

If these 2 things are solved then it'd be good to go/merge. Hope anyone can assist me on this.

2024-07-26 04:09 UTC, Zeffuro commented
Actually, option 1 works fine, I just didn't notice/realize that the default label adds a condition...
So it should be good to use/merge, 2 is more of a neat/performance thing.

2024-08-02 20:44 UTC, Zeffuro commented
Waiting for new Dalamud release I suppose that has job change event built in so I can move the keybind helper update on job change there and then it should be more performant too

2024-08-04 08:32 UTC, Zeffuro commented
This feature should be done and good to go/merge, for some reason the JobChange event wasn't merged/released with the last version of Dalamud so for now it only works on Staging but it works perfectly fine there.

We can merge when JobChange hits Dalamud Release

2024-08-06 04:26 UTC, Zeffuro commented
Changes are in live Dalamud.
@Tischel Can you look at this and merge if you agree with the PR :)

2024-11-16 08:53 UTC, Zeffuro commented
Made one small tweak and the functionality still works fine.
@Tischel Can you check and if you happen to not want this functionality or just find me code to be too bad you're free to just close it, this PR has been in limbo for over 4 months at this point.

2024-11-16 15:36 UTC, Tischel commented on DelvCD/Helpers/KeybindHelper.cs
> +
```suggestion

Singletons.Get<IClientState>().ClassJobChanged -= OnJobChanged;

```

2024-11-16 15:39 UTC, Tischel requested changes

2024-11-16 15:39 UTC, Tischel commented on DelvCD/PluginManager.cs
> +            ClientState.Login += OnLogin;
Unsubscribe from this in the dispose method

2024-11-16 15:39 UTC, Tischel commented on DelvCD/Helpers/KeybindHelper.cs
> +        var barId = addon->AddonActionBarBase.RaptureHotbarId;
Please use explicit types instead of `var` through out this file.

2024-11-16 16:05 UTC, Zeffuro commented
Thank you, made all the changes!

2024-11-16 16:15 UTC, merged